### ISSUE TITLE
No 3G and no sound on tilapia

### ISSUE THREAD

**Issue by e2002e** [AndDiSa/android_kernel_asus_grouper#5]
Hello, I used the linux tegra-3.4 branch and this works fine for some things like 80211 frame injection, but there is no mobile network as the sim card is not recognized, also there is no sound.
Can you help me out ?

**Comment by AndDiSa** [comment]
Unfortunately not, in addition this branch was never touched by myself. You can try https://github.com/AndDiSa/android_kernel_nvidia_tegra3/commits/ads-staging which was kind of working for Grouper.

**Comment by e2002e** [comment]
Ok Andisa, thanks for replying, in fact there is a working repo for the grouper/tilapia:
https://github.com/binkybear/android_kernel_asus_grouper-1
I am using unlegacy android kernel and had many issues with the wifi drivers (that even lead to reboots when using nethunter's nmap).
Also I could not get [bcmon](https://github.com/e2002e/bcmon2020) or [nexmon](https://github.com/e2002e/nexmon) to work. Now it does and there is sound and mobile network.
I am very glad. I suggest that you use this kernel for your projects as it might run without any special configuration. Having a kernel that is at least 3.2 is mandatory for chroot which is needed in applications like nethunter or linuxdeploy.
Also I'm apologizing for my quite cynical comment on xda (under the pseudonym of closeRanger).
I hope you be using this kernel for LineageOS too.

**Comment by AndDiSa** [comment]
@e2002e no problem at all. Unfortunately I do no have the the device anymore otherwise I would concentrate on the 3.4 kernel ... even if there were some issues with graphics the last time I played with it.
